/**
 * Firestore Repository Implementation for Money Transfer Service
 * ⏳ Used in production (Phase 7+)
 * 🔥 Uses Firebase Firestore for data storage
 * 🔄 Drop-in replacement for MoneyTransferJsonRepository
 *
 * To migrate from JSON to Firestore:
 * 1. Create MoneyTransferFirestoreRepository
 * 2. Change imports in API endpoints (use dependency injection or factory)
 * 3. Keep everything else the same!
 */

import {
  collection,
  query,
  where,
  orderBy,
  limit,
  getDocs,
  getDoc,
  addDoc,
  updateDoc,
  deleteDoc,
  doc,
  Timestamp,
  type Firestore,
} from 'firebase/firestore'
import type {
  MoneyTransferTransaction,
  MoneyTransferDailySummary,
  MoneyTransferBalance,
  IMoneyTransferRepository,
  FavoriteTransfer,
} from '~/types/repositories'

/**
 * Firestore Repository for Money Transfer Service
 * - Reads/writes data from/to Firestore
 * - Same interface as MoneyTransferJsonRepository
 * - Perfect for production with scaling needs
 */
export class MoneyTransferFirestoreRepository implements IMoneyTransferRepository {
  private db: Firestore
  private transactionsCollection = 'money_transfer_transactions'
  private summariesCollection = 'money_transfer_summaries'
  private balancesCollection = 'money_transfer_balances'

  constructor(db: Firestore) {
    this.db = db
  }

  /**
   * Initialize repository
   * In Firestore, this just validates connection
   */
  async init(): Promise<void> {
    try {
      // Test connection by getting one document from each collection
      const transQ = query(collection(this.db, this.transactionsCollection))
      await getDocs(transQ)

      const summQ = query(collection(this.db, this.summariesCollection))
      await getDocs(summQ)

      const balQ = query(collection(this.db, this.balancesCollection))
      await getDocs(balQ)

      console.log('✅ Firestore connection verified for Money Transfer Service')
    } catch (error) {
      console.error('❌ Firestore connection failed:', error)
      throw new Error('Failed to connect to Firestore')
    }
  }

  // ============================================================================
  // TRANSACTION OPERATIONS
  // ============================================================================

  /**
   * READ: Get single transaction by ID
   */
  async getTransaction(id: string): Promise<MoneyTransferTransaction> {
    const docRef = doc(this.db, this.transactionsCollection, id)
    const snapshot = await getDoc(docRef)

    if (!snapshot.exists()) {
      throw new Error(`Transaction with ID ${id} not found`)
    }

    return this.firestoreToTransaction(snapshot.data())
  }

  /**
   * READ: Get transactions for a specific date
   */
  async getTransactionsByDate(date: string): Promise<MoneyTransferTransaction[]> {
    const q = query(
      collection(this.db, this.transactionsCollection),
      where('date', '==', date)
    )

    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => this.firestoreToTransaction(doc.data()))
  }

  /**
   * READ: Get transactions by date range
   */
  async getTransactionsByDateRange(
    startDate: string,
    endDate: string
  ): Promise<MoneyTransferTransaction[]> {
    const start = new Date(startDate + 'T00:00:00')
    const end = new Date(endDate + 'T23:59:59')

    const q = query(
      collection(this.db, this.transactionsCollection),
      where('date', '>=', start),
      where('date', '<=', end)
    )

    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => this.firestoreToTransaction(doc.data()))
  }

  /**
   * READ: Get transactions by status
   */
  async getTransactionsByStatus(
    status: MoneyTransferTransaction['status']
  ): Promise<MoneyTransferTransaction[]> {
    const q = query(
      collection(this.db, this.transactionsCollection),
      where('status', '==', status)
    )

    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => this.firestoreToTransaction(doc.data()))
  }

  /**
   * READ: Get draft transactions for a date
   */
  async getDraftTransactions(date: string): Promise<MoneyTransferTransaction[]> {
    const q = query(
      collection(this.db, this.transactionsCollection),
      where('date', '==', date),
      where('status', '==', 'draft')
    )

    const snapshot = await getDocs(q)
    return snapshot.docs.map(doc => this.firestoreToTransaction(doc.data()))
  }

  /**
   * WRITE: Add new transaction
   */
  async addTransaction(
    transaction: Omit<MoneyTransferTransaction, 'id' | 'createdAt' | 'updatedAt'>
  ): Promise<MoneyTransferTransaction> {
    // Prepare data for Firestore
    const docData = this.transactionToFirestore({
      ...transaction,
      id: '', // Placeholder, will be generated by Firestore
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    })

    // Validate
    this.validateTransaction({
      ...transaction,
      id: '',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    } as MoneyTransferTransaction)

    // Add to Firestore
    const docRef = await addDoc(
      collection(this.db, this.transactionsCollection),
      docData
    )

    console.log(`✅ Added transaction: ${docRef.id}`)

    return {
      ...transaction,
      id: docRef.id,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    } as MoneyTransferTransaction
  }

  /**
   * WRITE: Update existing transaction
   */
  async updateTransaction(
    id: string,
    updates: Partial<MoneyTransferTransaction>
  ): Promise<MoneyTransferTransaction> {
    // Get existing transaction
    const existing = await this.getTransaction(id)

    // Prepare updates for Firestore
    const firestoreUpdates = this.transactionToFirestore({
      ...existing,
      ...updates,
      id: existing.id, // Always use original ID
      createdAt: existing.createdAt, // Never update
      updatedAt: new Date().toISOString(),
    })

    // Update in Firestore
    const docRef = doc(this.db, this.transactionsCollection, id)
    await updateDoc(docRef, firestoreUpdates)

    // Fetch and return updated transaction
    const docSnap = await getDoc(docRef)
    if (!docSnap.exists()) {
      throw new Error(`Transaction with ID ${id} not found after update`)
    }

    console.log(`✅ Updated transaction: ${id}`)
    return this.firestoreToTransaction(docSnap.data())
  }

  /**
   * WRITE: Delete transaction
   */
  async deleteTransaction(id: string): Promise<void> {
    const docRef = doc(this.db, this.transactionsCollection, id)
    await deleteDoc(docRef)

    console.log(`✅ Deleted transaction: ${id}`)
  }

  /**
   * WRITE: Complete draft transaction
   */
  async completeDraftTransaction(
    id: string,
    updates: Partial<MoneyTransferTransaction>
  ): Promise<MoneyTransferTransaction> {
    const transaction = await this.getTransaction(id)

    if (transaction.status !== 'draft') {
      throw new Error('Only draft transactions can be completed')
    }

    return this.updateTransaction(id, {
      ...updates,
      status: 'completed',
      completedAt: new Date().toISOString(),
    })
  }

  /**
   * READ: Get transaction count for a date
   */
  async getTransactionCount(date: string): Promise<number> {
    const q = query(
      collection(this.db, this.transactionsCollection),
      where('date', '==', date)
    )

    const snapshot = await getDocs(q)
    return snapshot.size
  }

  /**
   * READ: Get transaction count by status
   */
  async getTransactionCountByStatus(date: string, status: string): Promise<number> {
    const q = query(
      collection(this.db, this.transactionsCollection),
      where('date', '==', date),
      where('status', '==', status)
    )

    const snapshot = await getDocs(q)
    return snapshot.size
  }

  // ============================================================================
  // DAILY SUMMARY OPERATIONS
  // ============================================================================

  /**
   * READ: Get daily summary
   */
  async getDailySummary(date: string): Promise<MoneyTransferDailySummary | null> {
    const summaryId = `mtsum-${date}`
    const docRef = doc(this.db, this.summariesCollection, summaryId)
    const snapshot = await getDoc(docRef)

    if (!snapshot.exists()) {
      return null
    }

    return this.firestoreToSummary(snapshot.data())
  }

  /**
   * WRITE: Create daily summary
   */
  async createDailySummary(date: string): Promise<MoneyTransferDailySummary> {
    // Check if already exists
    const existing = await this.getDailySummary(date)
    if (existing) {
      throw new Error(`Summary for ${date} already exists`)
    }

    const summaryId = `mtsum-${date}`
    const summary: MoneyTransferDailySummary = {
      id: summaryId,
      date,
      step1: {
        status: 'in_progress',
        totalTransactions: 0,
        completedTransactions: 0,
        draftTransactions: 0,
        totalAmount: 0,
        totalCommission: 0,
      },
      workflowStatus: 'step1_in_progress',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }

    const docData = this.summaryToFirestore(summary)
    const docRef = doc(this.db, this.summariesCollection, summaryId)
    await updateDoc(docRef, docData).catch(async () => {
      // If document doesn't exist, create it
      await addDoc(collection(this.db, this.summariesCollection), {
        ...docData,
        id: summaryId,
      })
    })

    console.log(`✅ Created summary for ${date}`)
    return summary
  }

  /**
   * WRITE: Update daily summary
   */
  async updateDailySummary(
    date: string,
    updates: Partial<MoneyTransferDailySummary>
  ): Promise<MoneyTransferDailySummary> {
    const existing = await this.getDailySummary(date)
    if (!existing) {
      throw new Error(`Summary for ${date} not found`)
    }

    const updated = {
      ...existing,
      ...updates,
      id: existing.id,
      date: existing.date,
      updatedAt: new Date().toISOString(),
    } as MoneyTransferDailySummary

    const summaryId = `mtsum-${date}`
    const firestoreUpdates = this.summaryToFirestore(updated)
    const docRef = doc(this.db, this.summariesCollection, summaryId)

    await updateDoc(docRef, firestoreUpdates)

    console.log(`✅ Updated summary for ${date}`)
    return updated
  }

  // ============================================================================
  // BALANCE OPERATIONS
  // ============================================================================

  /**
   * READ: Get current balance for a date
   */
  async getCurrentBalance(date: string): Promise<MoneyTransferBalance> {
    let balance = await this.getBalance(date)

    if (!balance) {
      // Initialize with zero balance if doesn't exist
      balance = await this.initializeBalance(date)
    }

    return balance
  }

  /**
   * READ: Get balance for a date
   */
  private async getBalance(date: string): Promise<MoneyTransferBalance | null> {
    const balanceId = `mtbal-${date}`
    const docRef = doc(this.db, this.balancesCollection, balanceId)
    const snapshot = await getDoc(docRef)

    if (!snapshot.exists()) {
      return null
    }

    return this.firestoreToBalance(snapshot.data())
  }

  /**
   * WRITE: Initialize balance for a date
   */
  async initializeBalance(date: string): Promise<MoneyTransferBalance> {
    const balanceId = `mtbal-${date}`
    const balance: MoneyTransferBalance = {
      id: balanceId,
      date,
      bankAccount: 0,
      transferCash: 0,
      serviceFeeTransfer: 0,
      serviceFeeCash: 0,
      history: [],
      updatedAt: new Date().toISOString(),
    }

    const docData = this.balanceToFirestore(balance)
    const docRef = doc(this.db, this.balancesCollection, balanceId)

    await updateDoc(docRef, docData).catch(async () => {
      // If document doesn't exist, create it
      await addDoc(collection(this.db, this.balancesCollection), {
        ...docData,
        id: balanceId,
      })
    })

    console.log(`✅ Initialized balance for ${date}`)
    return balance
  }

  /**
   * WRITE: Update balance
   */
  async updateBalance(
    date: string,
    updates: Partial<MoneyTransferBalance>
  ): Promise<MoneyTransferBalance> {
    const existing = await this.getCurrentBalance(date)

    const updated = {
      ...existing,
      ...updates,
      id: existing.id,
      date: existing.date,
      updatedAt: new Date().toISOString(),
    } as MoneyTransferBalance

    const balanceId = `mtbal-${date}`
    const firestoreUpdates = this.balanceToFirestore(updated)
    const docRef = doc(this.db, this.balancesCollection, balanceId)

    await updateDoc(docRef, firestoreUpdates)

    console.log(`✅ Updated balance for ${date}`)
    return updated
  }

  // ============================================================================
  // WORKFLOW COMPLETION OPERATIONS
  // ============================================================================

  /**
   * WRITE: Complete Step 1 (Manager transaction recording)
   */
  async completeStep1(
    date: string,
    userId: string,
    userName: string
  ): Promise<MoneyTransferDailySummary> {
    // Get or create summary
    let summary = await this.getDailySummary(date)
    if (!summary) {
      summary = await this.createDailySummary(date)
    }

    // Get transactions for this date
    const transactions = await this.getTransactionsByDate(date)
    const completed = transactions.filter(t => t.status === 'completed')

    // Update summary
    return this.updateDailySummary(date, {
      step1: {
        ...summary.step1,
        status: 'completed',
        completedAt: new Date().toISOString(),
        completedBy: userId,
        completedByName: userName,
        totalTransactions: transactions.length,
        completedTransactions: completed.length,
        draftTransactions: transactions.filter(t => t.status === 'draft').length,
        totalAmount: completed.reduce((sum, t) => sum + t.amount, 0),
        totalCommission: completed.reduce((sum, t) => sum + (t.commission || 0), 0),
      },
      workflowStatus: 'step1_completed',
    })
  }

  /**
   * WRITE: Complete Step 2 (Manager cash verification)
   */
  async completeStep2(
    date: string,
    step2Data: MoneyTransferDailySummary['step2']
  ): Promise<MoneyTransferDailySummary> {
    const summary = await this.getDailySummary(date)
    if (!summary) {
      throw new Error(`Summary for ${date} not found`)
    }

    return this.updateDailySummary(date, {
      step2: {
        status: 'completed',
        completedAt: step2Data?.completedAt,
        completedBy: step2Data?.completedBy,
        completedByName: step2Data?.completedByName,
        expectedCash: step2Data?.expectedCash ?? { transferWithdrawal: 0, serviceFee: 0, total: 0 },
        actualCash: step2Data?.actualCash ?? { transferWithdrawal: 0, serviceFee: 0, total: 0 },
        differences: step2Data?.differences ?? { transferWithdrawal: 0, serviceFee: 0, total: 0 },
        verificationNotes: step2Data?.verificationNotes,
        hasDiscrepancies: step2Data?.hasDiscrepancies ?? false,
      },
      workflowStatus: 'step2_completed',
    })
  }

  /**
   * WRITE: Complete audit (Workflow 2.2)
   */
  async completeAudit(
    date: string,
    auditData: MoneyTransferDailySummary['auditorVerification']
  ): Promise<MoneyTransferDailySummary> {
    const summary = await this.getDailySummary(date)
    if (!summary) {
      throw new Error(`Summary for ${date} not found`)
    }

    return this.updateDailySummary(date, {
      auditorVerification: {
        status: 'completed',
        completedAt: auditData?.completedAt,
        completedBy: auditData?.completedBy,
        completedByName: auditData?.completedByName,
        transactionsVerified: auditData?.transactionsVerified ?? 0,
        transactionsWithIssues: auditData?.transactionsWithIssues ?? 0,
        bankStatementVerified: auditData?.bankStatementVerified ?? false,
        bankBalanceMatches: auditData?.bankBalanceMatches ?? false,
        auditNotes: auditData?.auditNotes ?? '',
        issuesFound: auditData?.issuesFound,
        auditResult: auditData?.auditResult ?? 'no_issues',
      },
      workflowStatus: 'audited',
    })
  }

  /**
   * WRITE: Owner approval (Workflow 2.3)
   */
  async approveByOwner(
    date: string,
    approvalData: MoneyTransferDailySummary['ownerApproval']
  ): Promise<MoneyTransferDailySummary> {
    const summary = await this.getDailySummary(date)
    if (!summary) {
      throw new Error(`Summary for ${date} not found`)
    }

    // Determine workflow status and approval status based on decision
    const decision = approvalData?.decision ?? 'approve'
    const workflowStatus: MoneyTransferDailySummary['workflowStatus'] =
      decision === 'request_correction' ? 'needs_correction' : 'approved'
    const approvalStatus: 'approved' | 'approved_with_notes' | 'correction_requested' =
      decision === 'approve'
        ? 'approved'
        : decision === 'approve_with_notes'
          ? 'approved_with_notes'
          : 'correction_requested'

    return this.updateDailySummary(date, {
      ownerApproval: {
        status: approvalStatus,
        completedAt: approvalData?.completedAt,
        completedBy: approvalData?.completedBy,
        completedByName: approvalData?.completedByName,
        decision,
        ownerNotes: approvalData?.ownerNotes,
      },
      workflowStatus,
    })
  }

  // ============================================================================
  // BALANCE EXTENDED OPERATIONS
  // ============================================================================

  /**
   * WRITE: Set opening balance for a date
   */
  async setOpeningBalance(date: string, amount: number, source: 'carryover' | 'manual', userId?: string): Promise<MoneyTransferBalance> {
    return this.updateBalance(date, {
      openingBalance: Number(amount),
      openingBalanceSetAt: new Date().toISOString(),
      openingBalanceSource: source,
      openingBalanceSetBy: userId,
    })
  }

  /**
   * READ: Get previous day's balance
   */
  async getPreviousDayBalance(date: string): Promise<MoneyTransferBalance | null> {
    // Find the most recent balance record with date strictly before the given date
    // that was actually initialized (has openingBalanceSource set).
    // Uses 'in' instead of '!= null' to avoid composite index requirement.
    const q = query(
      collection(this.db, this.balancesCollection),
      where('date', '<', date),
      where('openingBalanceSource', 'in', ['carryover', 'manual']),
      orderBy('date', 'desc'),
      limit(1)
    )
    const snap = await getDocs(q)
    if (snap.empty) return null
    return this.firestoreToBalance(snap.docs[0].data())
  }

  // ============================================================================
  // FAVORITES OPERATIONS
  // ============================================================================

  private favoritesCollection = 'money_transfer_favorites'

  /**
   * READ: Get all favorites
   */
  async getFavorites(): Promise<FavoriteTransfer[]> {
    const col = collection(this.db, this.favoritesCollection)
    const snap = await getDocs(col)
    return snap.docs.map(d => ({ id: d.id, ...d.data() } as FavoriteTransfer))
  }

  /**
   * READ: Get favorites by tab
   */
  async getFavoritesByTab(tab: 1 | 2 | 3 | 4 | 5): Promise<FavoriteTransfer[]> {
    const col = collection(this.db, this.favoritesCollection)
    const q = query(col, where('tab', '==', tab))
    const snap = await getDocs(q)
    return snap.docs.map(d => ({ id: d.id, ...d.data() } as FavoriteTransfer))
  }

  /**
   * WRITE: Add a new favorite
   */
  async addFavorite(data: Omit<FavoriteTransfer, 'id' | 'createdAt'>): Promise<FavoriteTransfer> {
    const col = collection(this.db, this.favoritesCollection)
    const newData = { ...data, createdAt: new Date().toISOString() }
    const docRef = await addDoc(col, newData)
    return { id: docRef.id, ...newData } as FavoriteTransfer
  }

  /**
   * WRITE: Update existing favorite
   */
  async updateFavorite(id: string, updates: Partial<Omit<FavoriteTransfer, 'id' | 'createdAt'>>): Promise<FavoriteTransfer> {
    const docRef = doc(this.db, this.favoritesCollection, id)
    await updateDoc(docRef, updates as Record<string, unknown>)
    const snap = await getDoc(docRef)
    if (!snap.exists()) throw new Error(`Favorite ${id} not found`)
    return { id: snap.id, ...snap.data() } as FavoriteTransfer
  }

  /**
   * WRITE: Delete a favorite
   */
  async deleteFavorite(id: string): Promise<void> {
    const docRef = doc(this.db, this.favoritesCollection, id)
    await deleteDoc(docRef)
  }

  // ============================================================================
  // HELPERS: Convert between Firestore and TypeScript
  // ============================================================================

  /**
   * Convert Firestore document to MoneyTransferTransaction
   */
  private firestoreToTransaction(data: any): MoneyTransferTransaction {
    return {
      ...data,
      createdAt: data.createdAt instanceof Timestamp ? data.createdAt.toDate().toISOString() : data.createdAt,
      updatedAt: data.updatedAt instanceof Timestamp ? data.updatedAt.toDate().toISOString() : data.updatedAt,
      completedAt: data.completedAt instanceof Timestamp ? data.completedAt.toDate().toISOString() : data.completedAt,
      datetime: data.datetime instanceof Timestamp ? data.datetime.toDate().toISOString() : data.datetime,
    } as MoneyTransferTransaction
  }

  /**
   * Convert MoneyTransferTransaction to Firestore format
   */
  private transactionToFirestore(transaction: MoneyTransferTransaction): any {
    return {
      ...transaction,
      createdAt: this.dateToTimestamp(transaction.createdAt),
      updatedAt: this.dateToTimestamp(transaction.updatedAt),
      completedAt: transaction.completedAt ? this.dateToTimestamp(transaction.completedAt) : null,
      datetime: this.dateToTimestamp(transaction.datetime),
      date: transaction.date, // Store as string for querying
    }
  }

  /**
   * Convert Firestore document to MoneyTransferDailySummary
   */
  private firestoreToSummary(data: any): MoneyTransferDailySummary {
    const converted = { ...data } as any

    // Convert timestamps in step1
    if (converted.step1?.completedAt instanceof Timestamp) {
      converted.step1.completedAt = converted.step1.completedAt.toDate().toISOString()
    }

    // Convert timestamps in step2
    if (converted.step2?.completedAt instanceof Timestamp) {
      converted.step2.completedAt = converted.step2.completedAt.toDate().toISOString()
    }

    // Convert timestamps in auditorVerification
    if (converted.auditorVerification?.completedAt instanceof Timestamp) {
      converted.auditorVerification.completedAt = converted.auditorVerification.completedAt.toDate().toISOString()
    }

    // Convert timestamps in ownerApproval
    if (converted.ownerApproval?.completedAt instanceof Timestamp) {
      converted.ownerApproval.completedAt = converted.ownerApproval.completedAt.toDate().toISOString()
    }

    // Convert timestamps at root level
    if (converted.createdAt instanceof Timestamp) {
      converted.createdAt = converted.createdAt.toDate().toISOString()
    }
    if (converted.updatedAt instanceof Timestamp) {
      converted.updatedAt = converted.updatedAt.toDate().toISOString()
    }

    return converted as MoneyTransferDailySummary
  }

  /**
   * Convert MoneyTransferDailySummary to Firestore format
   */
  private summaryToFirestore(summary: MoneyTransferDailySummary): any {
    const converted = { ...summary } as any

    // Convert timestamps
    if (converted.createdAt && !(converted.createdAt instanceof Timestamp)) {
      converted.createdAt = this.dateToTimestamp(converted.createdAt)
    }
    if (converted.updatedAt && !(converted.updatedAt instanceof Timestamp)) {
      converted.updatedAt = this.dateToTimestamp(converted.updatedAt)
    }

    // Convert nested timestamps
    if (converted.step1?.completedAt && !(converted.step1.completedAt instanceof Timestamp)) {
      converted.step1.completedAt = this.dateToTimestamp(converted.step1.completedAt)
    }
    if (converted.step2?.completedAt && !(converted.step2.completedAt instanceof Timestamp)) {
      converted.step2.completedAt = this.dateToTimestamp(converted.step2.completedAt)
    }
    if (converted.auditorVerification?.completedAt && !(converted.auditorVerification.completedAt instanceof Timestamp)) {
      converted.auditorVerification.completedAt = this.dateToTimestamp(converted.auditorVerification.completedAt)
    }
    if (converted.ownerApproval?.completedAt && !(converted.ownerApproval.completedAt instanceof Timestamp)) {
      converted.ownerApproval.completedAt = this.dateToTimestamp(converted.ownerApproval.completedAt)
    }

    return converted
  }

  /**
   * Convert Firestore document to MoneyTransferBalance
   */
  private firestoreToBalance(data: any): MoneyTransferBalance {
    const converted = { ...data } as any

    // Convert timestamps
    if (converted.updatedAt instanceof Timestamp) {
      converted.updatedAt = converted.updatedAt.toDate().toISOString()
    }

    // Convert history timestamps
    if (converted.history && Array.isArray(converted.history)) {
      converted.history = converted.history.map((entry: any) => ({
        ...entry,
        timestamp: entry.timestamp instanceof Timestamp ? entry.timestamp.toDate().toISOString() : entry.timestamp,
      }))
    }

    return converted as MoneyTransferBalance
  }

  /**
   * Convert MoneyTransferBalance to Firestore format
   */
  private balanceToFirestore(balance: MoneyTransferBalance): any {
    const converted = { ...balance } as any

    // Convert updatedAt
    if (converted.updatedAt && !(converted.updatedAt instanceof Timestamp)) {
      converted.updatedAt = this.dateToTimestamp(converted.updatedAt)
    }

    // Convert history timestamps
    if (converted.history && Array.isArray(converted.history)) {
      converted.history = converted.history.map((entry: any) => ({
        ...entry,
        timestamp: this.dateToTimestamp(entry.timestamp),
      }))
    }

    return converted
  }

  /**
   * Convert ISO string or Date to Firestore Timestamp
   */
  private dateToTimestamp(date: string | Date | undefined): Timestamp | null {
    if (!date) return null

    const dateObj = typeof date === 'string' ? new Date(date) : date
    return Timestamp.fromDate(dateObj)
  }

  /**
   * Validate transaction data
   */
  private validateTransaction(transaction: MoneyTransferTransaction): void {
    if (!transaction.date) throw new Error('Date is required')
    if (!transaction.datetime) throw new Error('DateTime is required')
    if (!transaction.transactionType) throw new Error('Transaction type is required (transfer, withdrawal, owner_deposit)')
    if (transaction.amount < 0) throw new Error('Amount cannot be negative')
    if ((transaction.commission || 0) < 0) throw new Error('Commission cannot be negative')
    if (!transaction.balanceImpact) throw new Error('Balance impact snapshot is required')
    if (!transaction.recordedBy) throw new Error('Recorded by user ID is required')
    if (!transaction.recordedByName) throw new Error('Recorded by user name is required')
  }
}

/**
 * Factory function to create repository instance
 * Usage: const repo = createMoneyTransferFirestoreRepository(db)
 */
export function createMoneyTransferFirestoreRepository(
  db: Firestore
): MoneyTransferFirestoreRepository {
  return new MoneyTransferFirestoreRepository(db)
}
